#!/bin/bash
set -x

sudo kubeadm init --cri-socket unix:/run/containerd/containerd.sock --pod-network-cidr=172.17.0.0/16
mkdir -p $HOME/.kube
sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config
sudo chown $(id -u):$(id -g) $HOME/.kube/config
kubectl apply -f kube-flannel.yml
